//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcerciseWebAppl.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Excercise
    {
        [Required(ErrorMessage = "Please Enter a Valid ID")]
        [Range(10, 100)]
        public int ExcerciseID { get; set; }


        [Required(ErrorMessage = "Please Enter You Name")]
        [StringLength(100, MinimumLength = 5, ErrorMessage = "Please enter less than 100 Charaters")]
        public string ExcerciseName { get; set; }

        [Required]
        public System.DateTime ExcerciseDate { get; set; }

        [Required]
        [Range(1, 120, ErrorMessage = "Please enter less than 100 Charaters")]
        public int ExcerciseDuration { get; set; }
    }
}
